name: Newman run

on: 
  push:
    branches:
      - main

jobs:
  newman:
    runs-on: Ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create dir for report
        run: |
          mkdir testArtifacts

      - name:  Install newman
        run: |
          npm install -g newman
          npm install -g newman-report-htmlextra

      - name: Run Test
        run : newman run ServeRest.postman_collection.json -e serveRest_env.postman_environment.json -r cli,htmlextra
        
      - name: Report
        uses: actions/upload-artifact@v4
        with:
          name: Report
          path: newman
